# Generated by Django 5.2.7 on 2026-10-07 20:28

import django.utils.timezone
import django_mongodb_backend.fields
import microadventures.domain.models.challenge
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sensory", "Sensory"),
                            ("sound", "Sound"),
                            ("culture", "Culture"),
                            ("nature", "Nature"),
                            ("people_watching", "People Watching"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Walk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=100)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("tired", "Tired"),
                            ("calm", "Calm"),
                            ("active", "Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minutes", models.PositiveSmallIntegerField()),
                ("weather", models.CharField(max_length=50)),
                ("swaps_used", models.PositiveSmallIntegerField(default=0)),
                (
                    "challenges",
                    django_mongodb_backend.fields.EmbeddedModelArrayField(
                        embedded_model=microadventures.domain.models.challenge.Challenge
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
