# Generated by Django 5.2.18 on 2026-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microadventures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
