# Generated by Django 5.2.18 on 2026-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microadventures", "0002_walk_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="story",
            field=models.TextField(blank=True, default=""),
        ),
    ]
